// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProject.Migrations
{
    [DbContext(typeof(MemberContext))]
    partial class MemberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProject.Models.Course", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseID = "IT3080",
                            CourseName = "Contemporary Programming",
                            FullName = "Michael Ahlers",
                            ProfessorName = "Dyllon Dekok"
                        },
                        new
                        {
                            Id = 2,
                            CourseID = "IT3080",
                            CourseName = "Contemporary Programming",
                            FullName = "Josh Anness",
                            ProfessorName = "Dyllon Dekok"
                        },
                        new
                        {
                            Id = 3,
                            CourseID = "IT3045",
                            CourseName = "Database Management II",
                            FullName = "Jeffrey Wallace",
                            ProfessorName = "Aditty Mutsuddi"
                        },
                        new
                        {
                            Id = 4,
                            CourseID = "IT3045",
                            CourseName = "Database Management II",
                            FullName = "Darrion Hoard",
                            ProfessorName = "Professor D"
                        },
                        new
                        {
                            Id = 5,
                            CourseID = "IT3080",
                            CourseName = "Database Management II",
                            FullName = "Bangyan Ju",
                            ProfessorName = "Dyllon Dekok"
                        },
                        new
                        {
                            Id = 6,
                            CourseID = "IT3071",
                            CourseName = "Network Security",
                            FullName = "Pranav Mahajan",
                            ProfessorName = "Professor Mark Stockman"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Food", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavoriteMealTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondFavoriteFood")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteFood = "Sushi",
                            FavoriteMealTime = "Dinner",
                            FullName = "Michael Ahlers",
                            SecondFavoriteFood = "Wings"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteFood = "Burger",
                            FavoriteMealTime = "Dinner",
                            FullName = "Josh Anness",
                            SecondFavoriteFood = "Pizza"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteFood = "Loaded Fries",
                            FavoriteMealTime = "Dinner",
                            FullName = "Jeffrey Wallace",
                            SecondFavoriteFood = "Salad"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteFood = "Pizza",
                            FavoriteMealTime = "Dinner",
                            FullName = "Darrion Hoard",
                            SecondFavoriteFood = "Burger"
                        },
                        new
                        {
                            Id = 5,
                            FavoriteFood = "Pizza",
                            FavoriteMealTime = "Dinner",
                            FullName = "Bangyan Ju",
                            SecondFavoriteFood = "Hot pot"
                        },
                        new
                        {
                            Id = 6,
                            FavoriteFood = "Cane's Fingers",
                            FavoriteMealTime = "Dinner",
                            FullName = "Pranav Mahajan",
                            SecondFavoriteFood = "Wings"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Hobby", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteHobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondFavoriteHobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyYouLikeThem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FavoriteHobby = "Board Games",
                            FullName = "Michael Ahlers",
                            SecondFavoriteHobby = "Video Games",
                            WhyYouLikeThem = "Great way to relax"
                        },
                        new
                        {
                            Id = 2,
                            FavoriteHobby = "Fishing",
                            FullName = "Josh Anness",
                            SecondFavoriteHobby = "Basketball",
                            WhyYouLikeThem = "I like being outside and staying active"
                        },
                        new
                        {
                            Id = 3,
                            FavoriteHobby = "Cooking",
                            FullName = "Jeffrey Wallace",
                            SecondFavoriteHobby = "Photography",
                            WhyYouLikeThem = "I like exploring"
                        },
                        new
                        {
                            Id = 4,
                            FavoriteHobby = "Cooking",
                            FullName = "Darrion Hoard",
                            SecondFavoriteHobby = "Jiu Jitsu",
                            WhyYouLikeThem = "I love to eat and learning new submission points"
                        },
                        new
                        {
                            Id = 5,
                            FavoriteHobby = "Cooking",
                            FullName = "Bangyan Ju",
                            SecondFavoriteHobby = "Swimming",
                            WhyYouLikeThem = "They make me feel happy"
                        },
                        new
                        {
                            Id = 6,
                            FavoriteHobby = "Playing Video Games",
                            FullName = "Pranav Mahajan",
                            SecondFavoriteHobby = "Playing Guitar",
                            WhyYouLikeThem = "Video games are a fun way to hang out with my friends, and guitar keeps my brain active."
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Sport", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FavoriteSport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("When")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FavoriteSport = "Football",
                            FullName = "Michael Ahlers",
                            When = new DateTime(2007, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2,
                            FavoriteSport = "Baseball",
                            FullName = "Josh Anness",
                            When = new DateTime(2009, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3,
                            FavoriteSport = "Swimming",
                            FullName = "Jeffrey Wallace",
                            When = new DateTime(2008, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4,
                            FavoriteSport = "Skateboarding",
                            FullName = "Darrion Hoard",
                            When = new DateTime(2005, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5,
                            FavoriteSport = "Snowboarding",
                            FullName = "Bangyan Ju",
                            When = new DateTime(2005, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6,
                            FavoriteSport = "Snooker",
                            FullName = "Pranav Mahajan",
                            When = new DateTime(2010, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FinalProject.Models.info", b =>
                {
                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Info");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthdate = new DateTime(1990, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Michael Ahlers",
                            YearInProgram = "Sophmore"
                        },
                        new
                        {
                            ID = 2,
                            Birthdate = new DateTime(2002, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Josh Anness",
                            YearInProgram = "Sophmore"
                        },
                        new
                        {
                            ID = 3,
                            Birthdate = new DateTime(2000, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Jeffrey Wallace",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            ID = 4,
                            Birthdate = new DateTime(1994, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Darrion Hoard",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            ID = 5,
                            Birthdate = new DateTime(2000, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Bangyan Ju",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            ID = 6,
                            Birthdate = new DateTime(2001, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "IT",
                            FullName = "Pranav Mahajan",
                            YearInProgram = "Sophmore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
